version: '3.1'
services:
  php:
    build:
      context: ./docker
      dockerfile: php.Dockerfile
    volumes:
      - './app:/var/www/html'
      - './docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini'
    depends_on:
      - mariadb

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    links:
      - 'php'
    volumes:
      - './app:/var/www/html'
      - './config/nginx:/etc/nginx/conf.d'

  mariadb:
    image: mariadb:10.3.9
    restart: 'on-failure'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpass
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'
